### ISSUE TITLE
Reset Step Counter

### ISSUE THREAD

**Issue by RuffaloLavoisier** [Open-Smartwatch/open-smartwatch-os#188]
I think we need to designate and initialize a specific section of the step counter. (The beginning of the week, the beginning of the month)

**Comment by simonmicro** [comment]
Fair point - I have seen #189 , but I do not think this would be fine with everyone. Could you add a config option to let the user choose at least between `Monday` / `Sunday` / `No reset`? This is because, some of my watches I'm not using very often and I would like to keep my "fitness-progress" :P . Additionally here in Germany the week starts on Monday.

Thanks in advance!

**Comment by RuffaloLavoisier** [comment]
> user choose at least between `Monday` / `Sunday` / `No reset`?

Good.. I see, Thank you
